name: Check

on:
  pull_request:
  push:

permissions:
  contents: read

jobs:
  check:
    name: Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.11", "3.12"]
    steps:
      # actions/checkout@v6
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10
      # actions/setup-python@v6
      - uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1
        with:
          python-version: ${{ matrix.python-version }}
      - run: ./scripts/check.sh
